import Head from 'next/head'
import Services from '../components/services'
import About from '../components/about'
import Nav from '../components/nav'
import Splash from '../components/splash'
import Resources from '../components/resources'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav></Nav>
      <Splash></Splash>
      <Services></Services>
        
        <About></About>
        <Resources></Resources>
    </div>
  )
}
 // style={{position:"absolute", top:"35vh"}}