import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import cecLogo from '../public/logolol.jpg'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <div className='container-fluid d-flex justify-content-center'>
          <div className="row">
          <ul className="nav">
            <li className="nav-item">
              <a className="nav-link active" href="#">Active</a>
            </li>
            <li className="nav-item">
              <a className="nav-link" href="#">Link</a>
            </li>
            <li className="nav-item">
              <a className="nav-link" href="#">Link</a>
            </li>
            <li className="nav-item">
              <a className="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
          </div>

          </div>
          <div className='container-fluid d-flex justify-content-end'  >
          <div className='row'>
            
            <h6>204 Breckenridge Lane, 40207 Louisville, Ky</h6>
            
          </div>
          </div>

          <div className='container-fluid d-flex justify-content-end'  >
          <div className='row'>
            
            <h6>(502) 899-7778</h6>
            
          </div>
          </div>
        
 
        <div className='container-fluid' style={{display:"flex", justifyContent:"center", alignItems:"center", paddingTop:"25vh"}}>
          <div className='row'>
            <div className='col-md-12'>
            <Image src={cecLogo} layout="responsive"/>
            <h1>Conrad Eye Centers</h1>
            <h2>Tim Conrad, MD</h2>
            </div>
          </div>

        </div>
        
      
    </div>
  )
}
 // style={{position:"absolute", top:"35vh"}}